unique_ids:
  forms: {}
  modules: {client_lib: MI74WRHZEU3VDKQIZ4UCXFJNEMZL6YBD, client_lib.crud: JB3C3DEWSFQH6J2CH25DIM2UP36GIVSR,
    client_lib.crud.cache: OCC3KR2JSE5YLP6V6B6JCOMMN5J6CJIW, client_lib.crud.mixins: 5R43HRVY4PC6DDTKV7OWUXSUCLPU3ZMT,
    client_lib.crud.particles: 3FCHR2V2YS75QLJVCZPCHVRCQ3XDLNBO}
  server_modules: {server_lib: VEUFN7KUGXABNY2V3LF4SZS3SCIJW6NU, server_lib.crud: HBTTU4EIFY54FXBLAMKEQ5L2IUYCS6ZK,
    server_lib.crud.persistence: RYOL7ZJRSWEMQVIQ2PGVR6SAVCBAK7OL, server_lib.crud.security: FSUYDLNY7OODT5CPMX3PVHMTXIAETE76}
  assets: {standard-page.html: WWT2ENU5ESFJKWAIPUEG47JYE2JVJ6DE, theme.css: JT4THXKOTHRMQQ42K6PDUIUDSJKMOVVR}
