unique_ids:
  forms: {}
  modules: {client_lib: LOEELEO4PG454UYVOFBVVRK2SRCRZXZT, client_lib.crud: HDXO3AA62XZWXUWWBWJF7ZEEA33M3LCU,
    client_lib.crud.particles: 3FCHR2V2YS75QLJVCZPCHVRCQ3XDLNBO}
  server_modules: {server_lib: TOSNN3SBC37SH643WHMGNIUHSDQQOGFM, server_lib.crud: VC6XM26S5BDTDJMBZNUZUJSANTKYTLYW,
    server_lib.crud.persistence: RYOL7ZJRSWEMQVIQ2PGVR6SAVCBAK7OL, server_lib.crud.security: FSUYDLNY7OODT5CPMX3PVHMTXIAETE76}
  assets: {standard-page.html: WWT2ENU5ESFJKWAIPUEG47JYE2JVJ6DE, theme.css: JT4THXKOTHRMQQ42K6PDUIUDSJKMOVVR}
